FROM docker.io/library/ubuntu:22.04

# Fix timezone issue
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get -y update && apt-get -y install build-essential \
	bison \
	zlib1g-dev \
	libtool \
	cmake \
	vim \
	gcc-multilib \
	g++-multilib \
	libc6-dev-i386 \
	autoconf \
	automake \
	curl \
	wget \
	git \
	make \
	unzip \
	flex \
	libgmp-dev \
	libmpfr-dev \
	libmpc-dev \
	texinfo

# Clone the repository
RUN git clone https://github.com/H0w1/CISB-dataset.git
WORKDIR CISB-dataset

# Run setup script
RUN bash ./env/auto_get_compiler.sh

# Install Python dependencies
RUN apt-get install -y python3-pip
RUN pip3 install -r requirements.txt
